multinode: false

modelArtifacts:
  # uri and name are set via MODEL env var in Justfile -> helmfile
  size: 150Gi
  authSecretName: "hf-secret"
  labels:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/guide: "agg"
    llm-d.ai/accelerator-variant: "gpu"
    llm-d.ai/accelerator-vendor: "amd"

routing:
  proxy:
    enabled: false
    targetPort: 8000

accelerator:
  type: amd

decode:
  create: true
  parallelism:
    tensor: 8
    data: 1
  replicas: 1
  extraConfig:
    hostNetwork: false
  monitoring:
    podmonitor:
      enabled: true
      portName: "vllm"
      path: "/metrics"
      interval: "30s"
  initContainers: 
    - name: qos-downgrade
      image: "quay.io/tms/poker:0.0.13" # dummy
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "exit 0"]
      resources: {}
  containers:
    - name: "vllm"
      image: ghcr.io/vcave/llm-d/llm-d-rocm:v0.4.7-debug
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
      modelCommand: vllmServe
      args:
        - "--disable-uvicorn-access-log"
        - "--gpu-memory-utilization"
        - "0.95"
      env:
        - name: HF_HOME
          value: "/model-cache"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
              optional: true
        - name: GPU_ARCHS
          value: "gfx942"
        - name: AITER_JIT_DIR
          value: "/aiter-cache"
      ports:
        - containerPort: 8000
          name: vllm
          protocol: TCP
      resources:
        limits:
          # amd.com/gpu: 8  # added automatically from parallelism + accelerator
          memory: 400Gi
          cpu: "32"
        requests:
          # amd.com/gpu: 8  # added automatically from parallelism + accelerator
          memory: 400Gi
          cpu: "32"
      mountModelVolume: false
      volumeMounts:
        - name: metrics-volume
          mountPath: /.config
        - name: shm
          mountPath: /dev/shm
        - name: torch-compile-cache
          mountPath: /.cache
        - name: hf-cache
          mountPath: /model-cache
        - name: aiter-cache
          mountPath: /aiter-cache
      startupProbe:
        httpGet:
          path: /v1/models
          port: vllm
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 60
      livenessProbe:
        httpGet:
          path: /health
          port: vllm
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 30
      readinessProbe:
        httpGet:
          path: /v1/models
          port: vllm
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: "20Gi"
    - name: torch-compile-cache
      emptyDir: {}
    - name: hf-cache
      hostPath:
        path: /mnt/nvme/models
        type: DirectoryOrCreate
    - name: aiter-cache
      hostPath:
        path: /mnt/nvme/cache
        type: DirectoryOrCreate

prefill:
  create: false
