#!/usr/bin/env python3
"""Generate NIC (SR-IOV RDMA VF) values YAML for glm-disagg.

Reads DECODE_TP and PREFILL_TP from env (or defaults 8/4), outputs a YAML file
suitable as a Helm values override with podAnnotations and resource requests.

Usage:
  DECODE_TP=4 PREFILL_TP=2 python3 scripts/gen-nic-values.py
  Output written to ms/values-nic-generated.yaml
"""

import os
import sys
from pathlib import Path

def main():
    decode_tp = int(os.environ.get("DECODE_TP", "8"))
    prefill_tp = int(os.environ.get("PREFILL_TP", "4"))

    def networks_json(n: int) -> str:
        entries = [
            f'{{"name":"sriov-rdma-vf","namespace":"default","interface":"net{i}"}}'
            for i in range(1, n + 1)
        ]
        return "[" + ", ".join(entries) + "]"

    yaml_content = f"""# Generated by gen-nic-values.py - do not edit
# DECODE_TP={decode_tp} PREFILL_TP={prefill_tp}
# nvidia.com/sriov-rdma-vf resources are set via helmfile --set (merge into existing)

decode:
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: |
      {networks_json(decode_tp)}

prefill:
  podAnnotations:
    k8s.v1.cni.cncf.io/networks: |
      {networks_json(prefill_tp)}
"""

    out_path = Path(__file__).resolve().parent.parent / "ms" / "values-nic-generated.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml_content)
    print(f"Wrote {out_path} (decode={decode_tp} prefill={prefill_tp})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())

